from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from pptx import Presentation
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches as PptInches, Pt as PptPt
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.lib import colors


RED = "C40000"
BLACK = "0A0A0A"
DARK = "171717"
LIGHT = "F2F2F2"


def _safe_filename(name: str, extension: str) -> str:
    stem = re.sub(r"[^A-Za-z0-9._ -]+", "_", name).strip(" ._") or "dpn_ai_output"
    if not stem.lower().endswith(extension):
        stem += extension
    return stem


class DocumentFactory:
    def __init__(self, workspace: Path):
        self.workspace = workspace.resolve()
        self.output_dir = self.workspace / "generated"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _target(self, filename: str, extension: str) -> Path:
        target = (self.output_dir / _safe_filename(filename, extension)).resolve()
        target.relative_to(self.workspace)
        return target

    def create_docx(self, filename: str, title: str, sections: list[dict[str, Any]], author: str = "DPN AI") -> dict[str, Any]:
        target = self._target(filename, ".docx")
        doc = Document()
        section = doc.sections[0]
        section.top_margin = Inches(0.65)
        section.bottom_margin = Inches(0.65)
        section.left_margin = Inches(0.75)
        section.right_margin = Inches(0.75)

        styles = doc.styles
        styles["Normal"].font.name = "Aptos"
        styles["Normal"].font.size = Pt(10.5)
        styles["Title"].font.name = "Aptos Display"
        styles["Title"].font.size = Pt(28)
        styles["Title"].font.bold = True
        styles["Title"].font.color.rgb = RGBColor(196, 0, 0)
        for style_name, size in (("Heading 1", 18), ("Heading 2", 14)):
            styles[style_name].font.name = "Aptos Display"
            styles[style_name].font.size = Pt(size)
            styles[style_name].font.bold = True
            styles[style_name].font.color.rgb = RGBColor(196, 0, 0)

        title_p = doc.add_paragraph(style="Title")
        title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_p.add_run(title)
        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run(f"Prepared by {author}")
        run.bold = True
        run.font.color.rgb = RGBColor(40, 40, 40)
        doc.add_paragraph("DPN TECHNOLOGY • LOCAL AI OPERATIONS", style=None).alignment = WD_ALIGN_PARAGRAPH.CENTER

        for item in sections:
            heading = str(item.get("heading", "Section")).strip()
            level = int(item.get("level", 1))
            doc.add_heading(heading, level=max(1, min(level, 2)))
            body = item.get("body", "")
            if isinstance(body, list):
                for bullet in body:
                    doc.add_paragraph(str(bullet), style="List Bullet")
            else:
                for paragraph in str(body).split("\n\n"):
                    if paragraph.strip():
                        doc.add_paragraph(paragraph.strip())
            table_data = item.get("table")
            if isinstance(table_data, list) and table_data:
                rows = [row if isinstance(row, list) else [row] for row in table_data]
                width = max(len(row) for row in rows)
                table = doc.add_table(rows=len(rows), cols=width)
                table.style = "Table Grid"
                for r, row in enumerate(rows):
                    for c in range(width):
                        text = str(row[c]) if c < len(row) else ""
                        table.cell(r, c).text = text
                        if r == 0:
                            for cell_run in table.cell(r, c).paragraphs[0].runs:
                                cell_run.bold = True
                                cell_run.font.color.rgb = RGBColor(255, 255, 255)
                            table.cell(r, c)._tc.get_or_add_tcPr().append(
                                __import__("docx").oxml.parse_xml(
                                    f'<w:shd {__import__("docx").oxml.ns.nsdecls("w")} w:fill="{RED}"/>'
                                )
                            )
        core = doc.core_properties
        core.title = title
        core.author = author
        core.subject = "Generated by DPN AI"
        doc.save(target)
        return {"ok": True, "path": target.relative_to(self.workspace).as_posix(), "type": "docx"}

    def create_xlsx(self, filename: str, title: str, sheets: list[dict[str, Any]]) -> dict[str, Any]:
        target = self._target(filename, ".xlsx")
        workbook = Workbook()
        workbook.remove(workbook.active)
        for index, sheet_spec in enumerate(sheets or [{"name": "DPN AI", "rows": [[title]]}]):
            name = str(sheet_spec.get("name", f"Sheet {index + 1}"))[:31]
            ws = workbook.create_sheet(title=name)
            rows = sheet_spec.get("rows", [])
            for r_index, row in enumerate(rows, start=1):
                values = row if isinstance(row, list) else [row]
                for c_index, value in enumerate(values, start=1):
                    cell = ws.cell(r_index, c_index, value)
                    cell.alignment = Alignment(vertical="top", wrap_text=True)
                    if r_index == 1:
                        cell.font = Font(bold=True, color="FFFFFF")
                        cell.fill = PatternFill("solid", fgColor=RED)
            if not rows:
                ws["A1"] = title
                ws["A1"].font = Font(bold=True, color="FFFFFF")
                ws["A1"].fill = PatternFill("solid", fgColor=RED)
            ws.freeze_panes = "A2"
            ws.auto_filter.ref = ws.dimensions
            for column in range(1, ws.max_column + 1):
                max_length = 0
                for cell in ws[get_column_letter(column)]:
                    max_length = max(max_length, len(str(cell.value or "")))
                ws.column_dimensions[get_column_letter(column)].width = min(max(max_length + 2, 12), 50)
            ws.sheet_view.showGridLines = False
        workbook.save(target)
        return {"ok": True, "path": target.relative_to(self.workspace).as_posix(), "type": "xlsx"}

    def create_pptx(self, filename: str, title: str, slides: list[dict[str, Any]]) -> dict[str, Any]:
        target = self._target(filename, ".pptx")
        presentation = Presentation()
        presentation.slide_width = PptInches(13.333)
        presentation.slide_height = PptInches(7.5)

        def style_background(slide) -> None:
            fill = slide.background.fill
            fill.solid()
            fill.fore_color.rgb = __import__("pptx").dml.color.RGBColor(10, 10, 10)
            accent = slide.shapes.add_shape(1, 0, 0, PptInches(0.18), presentation.slide_height)
            accent.fill.solid()
            accent.fill.fore_color.rgb = __import__("pptx").dml.color.RGBColor(196, 0, 0)
            accent.line.fill.background()

        title_slide = presentation.slides.add_slide(presentation.slide_layouts[6])
        style_background(title_slide)
        title_box = title_slide.shapes.add_textbox(PptInches(0.85), PptInches(2.35), PptInches(11.7), PptInches(2.2))
        paragraph = title_box.text_frame.paragraphs[0]
        paragraph.text = title
        paragraph.font.name = "Aptos Display"
        paragraph.font.size = PptPt(38)
        paragraph.font.bold = True
        paragraph.font.color.rgb = __import__("pptx").dml.color.RGBColor(255, 255, 255)
        paragraph.alignment = PP_ALIGN.CENTER
        sub = title_slide.shapes.add_textbox(PptInches(1.8), PptInches(4.65), PptInches(9.8), PptInches(0.6))
        sp = sub.text_frame.paragraphs[0]
        sp.text = "DPN AI • DPN TECHNOLOGY"
        sp.font.size = PptPt(17)
        sp.font.bold = True
        sp.font.color.rgb = __import__("pptx").dml.color.RGBColor(196, 0, 0)
        sp.alignment = PP_ALIGN.CENTER

        for item in slides:
            slide = presentation.slides.add_slide(presentation.slide_layouts[6])
            style_background(slide)
            heading = slide.shapes.add_textbox(PptInches(0.75), PptInches(0.45), PptInches(11.8), PptInches(0.75))
            hp = heading.text_frame.paragraphs[0]
            hp.text = str(item.get("title", "DPN AI"))
            hp.font.name = "Aptos Display"
            hp.font.size = PptPt(28)
            hp.font.bold = True
            hp.font.color.rgb = __import__("pptx").dml.color.RGBColor(196, 0, 0)

            body_box = slide.shapes.add_textbox(PptInches(0.95), PptInches(1.4), PptInches(11.3), PptInches(5.5))
            text_frame = body_box.text_frame
            text_frame.word_wrap = True
            bullets = item.get("bullets")
            if not isinstance(bullets, list):
                bullets = [item.get("body", "")]
            for i, bullet in enumerate(bullets):
                p = text_frame.paragraphs[0] if i == 0 else text_frame.add_paragraph()
                p.text = str(bullet)
                p.font.name = "Aptos"
                p.font.size = PptPt(21 if len(bullets) <= 5 else 17)
                p.font.color.rgb = __import__("pptx").dml.color.RGBColor(240, 240, 240)
                p.level = 0
                p.space_after = PptPt(12)
        presentation.save(target)
        return {"ok": True, "path": target.relative_to(self.workspace).as_posix(), "type": "pptx"}

    def create_pdf(self, filename: str, title: str, sections: list[dict[str, Any]]) -> dict[str, Any]:
        target = self._target(filename, ".pdf")
        styles = getSampleStyleSheet()
        styles.add(ParagraphStyle(name="DPNTitle", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=24, leading=28, textColor=colors.HexColor("#C40000"), spaceAfter=18))
        styles.add(ParagraphStyle(name="DPNHeading", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=15, leading=18, textColor=colors.HexColor("#C40000"), spaceBefore=12, spaceAfter=7))
        styles.add(ParagraphStyle(name="DPNBody", parent=styles["BodyText"], fontName="Helvetica", fontSize=10, leading=14, textColor=colors.HexColor("#111111"), spaceAfter=8))
        story: list[Any] = [Paragraph(title, styles["DPNTitle"]), Paragraph("DPN AI • DPN TECHNOLOGY", styles["DPNBody"]), Spacer(1, 0.15 * inch)]
        for section in sections:
            story.append(Paragraph(str(section.get("heading", "Section")), styles["DPNHeading"]))
            body = section.get("body", "")
            if isinstance(body, list):
                for item in body:
                    story.append(Paragraph(f"• {item}", styles["DPNBody"]))
            else:
                for paragraph in str(body).split("\n\n"):
                    if paragraph.strip():
                        story.append(Paragraph(paragraph.strip().replace("\n", "<br/>"), styles["DPNBody"]))
            table_data = section.get("table")
            if isinstance(table_data, list) and table_data:
                table = Table(table_data, repeatRows=1, hAlign="LEFT")
                table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#C40000")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#777777")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F2F2F2")]),
                    ("LEFTPADDING", (0, 0), (-1, -1), 5),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ]))
                story.append(table)
                story.append(Spacer(1, 0.15 * inch))
        doc = SimpleDocTemplate(str(target), pagesize=letter, rightMargin=0.6*inch, leftMargin=0.6*inch, topMargin=0.6*inch, bottomMargin=0.6*inch, title=title, author="DPN AI")
        doc.build(story)
        return {"ok": True, "path": target.relative_to(self.workspace).as_posix(), "type": "pdf"}